#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | ssl-client:help)
    help_content_func () {
      declare desc="return help_content string"
      cat<<help_content
    ssl-client <app> <ca.cert, Install CA and enable SSL client authentication
    ssl-client:remove <app>, Remove CA and disable SSL client authentication
    ssl-client:stapling-file <app> <stapling.der, Install a stapling file and configure nginx accordingly
    ssl-client:remove-stapling-file <app>, Remove an existing stapling file if any

help_content
    }

    if [[ $1 = "ssl-client:help" ]] ; then
        echo -e 'Usage: dokku ssl-client[:remove] [<app>]'
        echo ''
        echo 'Enable SSL client authentication on <app>.'
        echo ''
        echo 'Example:'
        echo ''
        echo '$ dokku ssl-client <ca.crt'
        echo ''
        echo 'The SSL client certificate must comply with the format expected by the'
        echo 'ssl_client_certificate nginx directive'
        echo ''
        echo 'Additional commands:'
        help_content_func | sort | column -c2 -t -s,
    else
        help_content_func
    fi
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
