#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

ssl_client_main_cmd() {
  declare desc="Install SSL CA certificate and activate authentication"
  local cmd="ssl-client"
  # Support --app/$DOKKU_APP_NAME flag
  # Use the following lines to reorder args into "$cmd $DOKKU_APP_NAME $@""
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@
  ##

  [[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
  verify_app_name "$2"
  local APP="$2";

  cert=`cat /dev/stdin`
  echo "$cert" > $DOKKU_ROOT/$APP/ssl-client.ca

  mkdir -p $DOKKU_ROOT/$APP/nginx.conf.d

  cat <<EOF > $DOKKU_ROOT/$APP/nginx.conf.d/ssl-client.conf
    ssl_client_certificate $DOKKU_ROOT/$APP/ssl-client.ca;
    ssl_verify_client on;
EOF

}

ssl_client_main_cmd "$@"
