#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

ssl_client_remove_cmd() {
  declare desc="Remove SSL CA certificate and deactivate authentication"
  local cmd="ssl-client:remove"
  # Support --app/$DOKKU_APP_NAME flag
  # Use the following lines to reorder args into "$cmd $DOKKU_APP_NAME $@""
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@
  ##

  [[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
  verify_app_name "$2"
  local APP="$2";

  if [ -f "$DOKKU_ROOT/$APP/ssl-client.ca" ]; then
    rm "$DOKKU_ROOT/$APP/ssl-client.ca"
  else
    echo "No CA found"
    exit 1
  fi

  if [ -f "$DOKKU_ROOT/$APP/nginx.conf.d/ssl-client.conf" ]; then
    rm "$DOKKU_ROOT/$APP/nginx.conf.d/ssl-client.conf"
  else
    echo "No ssl-client nginx configuration found"
    exit 1
  fi
  
}

ssl_client_remove_cmd "$@"
