#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

ssl_client_remove_crl_cmd() {
  declare desc="Removes an existing CRL file if any"
  local cmd="ssl-client:remove-crl"
  # Support --app/$DOKKU_APP_NAME flag
  # Use the following lines to reorder args into "$cmd $DOKKU_APP_NAME $@""
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@
  ##

  [[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
  verify_app_name "$2"
  local APP="$2";

  if [ -f "$DOKKU_ROOT/$APP/ssl-crl.pem" ]; then
    rm "$DOKKU_ROOT/$APP/ssl-crl.pem"
  else
    echo "No CRL file found"
  fi

   cat <<EOF > $DOKKU_ROOT/$APP/nginx.conf.d/ssl-client.conf
    ssl_client_certificate $DOKKU_ROOT/$APP/ssl-client.ca;
    ssl_verify_client on;
EOF

}

ssl_client_remove_crl_cmd "$@"
